# Generated by Django 4.1 on 2023-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
